# name: Selenium C# Chrome Test

# on:
#   push:
#     branches: [ main ]
#   workflow_dispatch:
#   schedule:
#     - cron: '0 11 * * 2,6'

# defaults:
#   run:
#     working-directory: Selenium-Nunit-Extent

# jobs:
#   test:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: 7.0.x

#       - name: Build the Selenium-Nunit-Extent project
#         run: dotnet build

#       - name: Run the Selenium-Nunit-Extent tests
#         run: dotnet test --no-build

name: Selenium C# Chrome Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 2,6'

defaults:
  run:
    working-directory: Selenium-Nunit-Extent

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: '113'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build the Selenium-Nunit-Extent project
        run: dotnet build

      - name: Run the Selenium-Nunit-Extent tests
        run: dotnet test --no-build

