name: Selenium C# Chrome Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Build the Selenium-NUnit-Extent project
        run: dotnet build

      - name: Run the Selenium-NUnit-Extent tests
        run: dotnet test --no-build
