name: Selenium C# Chrome Test

on:
  push:
    branches:
      - main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore Selenium-Nunit-Extent.csproj

      - name: Build the example project
        run: dotnet build

      - name: Run the example tests
        run: dotnet test --no-build
