name: Selenium C# Chrome Test

on:
  push:
    branches:
      - main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Selenium-Nunit-Extent.csproj

    - name: Build the project
      run: dotnet build Selenium-Nunit-Extent.csproj /p:Configuration=Release

    - name: Install ChromeDriver
      run: |
        Invoke-WebRequest "https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_win64.zip" -OutFile chromedriver.zip
        Expand-Archive chromedriver.zip chromedriver

    - name: Run tests
      run: dotnet test Selenium-Nunit-Extent.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Publish code coverage results
      uses: actions-github/publish-code-coverage-action@v1
      with:
        path-to-coverage: "**/coverage.opencover.xml"
